### ISSUE TITLE
go get metadata should point at github not gerrithub

### ISSUE THREAD

**Issue by rogpeppe** [cue-labs/oci#21]
From a request on Slack:

The "go get" metadata for `cuelabs.dev/go/oci` should point to https://github.com/cue-labs/oci not https://review.gerrithub.io/cue-labs/oci so that links to source code on https://pkg.go.dev/cuelabs.dev/go/oci/ociregistry work correctly.

**Comment by tianon** [comment]
Oh, it appears that's in Git at https://github.com/cue-labs/cuelabs.dev-pub/blob/main/go/oci/index.html & https://github.com/cue-labs/cuelabs.dev-pub/blob/main/go/oci/ociregistry.html ? :eyes:

**Comment by myitcv** [comment]
I've raised https://github.com/golang/go/issues/65512 to request that the pkg.go.dev caches are manually cleared in this instance (see the linked issue that confirms this is still a manual step)

**Comment by myitcv** [comment]
Will close when the caches are cleared and this works properly.

**Comment by tianon** [comment]
Not sure if we got a cache _clear_, but I think the recent commit gave us a cache _bust_ which is almost as good! :smile:

https://pkg.go.dev/cuelabs.dev/go/oci/ociregistry (now with functional source code links! :heart:)

**Comment by myitcv** [comment]
> Not sure if we got a cache _clear_, but I think the recent commit gave us a cache _bust_ which is almost as good! 😄

Great!
