### ISSUE TITLE
Planning and design?

### ISSUE THREAD

**Issue by vsoch** [cue-labs/oci#9]
Heyo! 👋 I was looking for something like this - basically an SDK in go to add endpoints to an application. It looks like you’ve recently moved it over and are making a lot of changes. I was wondering if you could share your plan and if/when this would be ready for use? Are the basic endpoints done and you are adding bells and whistles?

**Comment by myitcv** [comment]
cc @rogpeppe

**Comment by rogpeppe** [comment]
Most of the plan is now complete, so I'm going to close this issue for now.
